# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77fa099e69cfb9070e1f4efac20de64c1cfe159b57c2242c518acb3b3e1d22e7bc212b79001ceedbe4e4442619db88c02c13d5865c605568e940a0f2ba642f08

test:
  secret_key_base: 64dbc56f8cab1df0b001c6fd1aa49d1b97a147d2c6b6a55cc438a3c5c19c56eedd2271e78804007ac0917c98c17c7a9b9868ef6f3e029df2281037116375893c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
